title: Mohammed Alshehri
description: Publications and research notes
url: "https://mohammed840.github.io"
baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  parse_block_html: true
  parse_span_html: true
collections:
  projects:
    output: true
    permalink: /projects/:name/
  blogs:
    output: true
    permalink: /blogs/:name/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: paper
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
  - scope:
      path: ""
    values:
      layout: default
